### ISSUE TITLE
Identically decode from `runtime.RawExtension.Raw` to `api.RsyslogRelpConfig`

### ISSUE THREAD

**Issue by Kostov6** [gardener/gardener-extension-shoot-rsyslog-relp#202]
**How to categorize this issue?**

/area quality
/kind enhancement

**What would you like to be added**:
 Let's do the decoding from `runtime.RawExtension.Raw` to `api.RsyslogRelpConfig` identically in all places. We can do it through:
-  a helper function. Let's move `decodeRsyslogRelpConfig` to `pkg/apis/rsyslog/helper/helpers.go` 
- use `extensions/pkg/util/serialization.go@Decode`

https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/8d1601a4d5106d8e579de220015780f1d136b4f4/pkg/controller/lifecycle/actuator.go#L60-L63

**Why is this needed**:
Minor code simplification

**Comment by plkokanov** [comment]
What about simply using [`runtime.DecodeInto`](https://github.com/kubernetes/apimachinery/blob/a8f449e276fe566efddb149992049c78f0088492/pkg/runtime/codec.go#L62-L71)? It seems to do the same thing as `extensions/pkg/util/serialization.go@Decode` but a bit simpler.

Note that you could also adapt the decoding of the `rsyslog.Audit` config: https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/bfe2cf67022962add01f28dc19c0256f99f4b1f3/pkg/admission/validator/shoot.go#L166-L171 and https://github.com/gardener/gardener-extension-shoot-rsyslog-relp/blob/bfe2cf67022962add01f28dc19c0256f99f4b1f3/pkg/webhook/operatingsystemconfig/auditd.go#L74-L78

Also let's reuse the same package name everywhere.
